env: test

spring:
  application:
    name: order-server      

server: 
  port: 8082                    

feign:
  compression:
    request:
      enabled: true
      min-request-size: 2048
      mime-types:
      - application/json
      - application/xml
      - text/xml
    response:
      enabled: true

      
      
      
